### PR TITLE
Initial commit.

### PR DESCRIPTION
**Pull request by donlockhart**
We are moving the web vehicle gateway into its own repo, following the pattern of the store service/gateway.

### CODE REVIEW

**Comment by mariagullickson** [comment]
Hmm...I thought we were ultimately trying to move everything to github.carmax.com.  Was I wrong?  Seems odd that we are creating new repos on github.com.

**Comment by mariagullickson** [comment]
When we split out the gateway, what is the plan for ARM templates?  Seems like the azure provisioning bits for the gateway should be in this repo too.

**Comment by donlockhart** [comment]
Yeah, I'm not quite sure of the distinction between the two.  @PallaviAthale created the repo for me - maybe she can share the thought process.

**Comment by donlockhart** [comment]
I imagine the ARM templates will get there own repo as well - at least that's the way stores is set up.

**Comment by mariagullickson** [comment]
It's not unusual for me to want to search across our codebase to see where libraries are being used and such.  It's annoying to always have to do 2 searches in 2 different githubs.  (Not even trying to get into subversion.)

**Comment by mariagullickson** [comment]
Oh, you are right - just saw PT-700 to pull ARM templates out into another repo.  Okay that makes sense.

**Comment by mariagullickson** [comment]
Thumbs up on what's in this repo, except for the question of whether it belongs in github.carmax.com.

**Comment by PallaviAthale** [comment]
@mariagullickson, web vehicle was started prior to GHE, so we started it on GitHub.com. Splitting the gateway out, I wanted to keep all web vehicle repos together instead of having some in GitHub.com and others in GHE. Anything new should be added to GHE unless we need non-CarMax folks have access to it (e.g. original plan was to have Marcus contribute to Search service).

**Comment by mariagullickson** [comment]
Is there a plan to move old stuff (that doesn't need to be shared) over to GTE?  Should I put a card in ideas to move vehicle service stuff to GTE?  It's annoying having things spread across different githubs.

**Comment by PallaviAthale** [comment]
Actually, @donlockhart and I were just talking about it too - sounds like right now is a good time to tackle that just because we are going to have to redo a lot of TC builds for the new repos, so it makes sense to just move everything web vehicle to GHE and create the ARM repo there as well.

Why don't we merge this PR, and I'll update the ARM repo card to include: 
1. migrating gateway and service repo to GHE 
2. create new repo for ARM in GHE
3. create/update the builds

**Comment by mariagullickson** [comment]
That makes sense.  Thanks!

**Pull request merged**
